name: Make Release

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build apk
        run: ./gradlew assembleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: app/build/outputs/apk/debug/app-debug.apk
      - name: Build bundle
        run: ./gradlew bundleDebug
      - name: Upload bundle
        uses: actions/upload-artifact@v1
        with:
          name: bundle
          path: app/build/outputs/bundle/debug/app-debug.aab
  release:
    name: Release Package
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download APK from build
        uses: actions/download-artifact@v1
        with:
          name: apk
      - name: Download Bundle from build
        uses: actions/download-artifact@v1
        with:
          name: bundle
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: MonkeyTest ${{ github.run_number }}
      - name: Upload Release Package
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "apk/app-debug.apk bundle/app-bundle.aab"
          asset_name: app-debug.apk
          asset_content_type: application/zip
