name: Make Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: tag for release
        required: true
      name:
        description: name for release
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build apk
        run: ./gradlew assembleDebug
      - name: Rename Apk
        run: mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/app-debug${{ github.event.inputs.tag }}.apk
      - name: Build bundle
        run: ./gradlew bundleDebug
      - name: Rename bundle
        run: mv app/build/outputs/bundle/debug/app-debug.aab app/build/outputs/bundle/debug/app-debug${{ github.event.inputs.tag }}.aab
      - name: upload artefact to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: copypasteearth/MonkeyTest
          gitReleaseNotes: true
          releaseNotes: true
          token: ${{secrets.APP_CENTER_TOKEN}}
          group: Testers;Collaborators
          file: app/build/outputs/apk/debug/app-debug${{ github.event.inputs.tag }}.apk
          notifyTesters: true
          debug: false
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag }}
          name: ${{ github.event.inputs.name }}
          generate_release_notes: true
          files: |
            app/build/outputs/apk/debug/app-debug${{ github.event.inputs.tag }}.apk
            app/build/outputs/bundle/debug/app-debug${{ github.event.inputs.tag }}.aab
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_REPOSITORY: copypasteearth/MonkeyTest
