name: Make Release

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build apk
        run: ./gradlew assembleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: app/build/outputs/apk/debug/app-debug.apk
      - name: Build bundle
        run: ./gradlew bundleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: bundle
          path: app/build/outputs/bundle/debug/app-debug.aab
      - name: Upload bundle
        uses: actions/upload-artifact@v1
        with:
          name: bundle
          path: app/build/outputs/bundle/debug/app-debug.aab
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
              apk/app-debug.apk
              bundle/app-bundle.aab
